name: Build Package

env:
  PYTHON_MAIN_VERSION: "3.10"

on: [push]

jobs:
  build-package:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Prepare cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build package
      run: |
        pip install wheel setuptools
        python setup.py sdist bdist_wheel
    - name: Install package
      run: |
        pip install .
        pip list
    - name: Lint with flake8
      uses: py-actions/flake8@v2
      with:
        exclude: "*/__init__.py"
        max-line-length: "120"
    - name: Upload package artifact
      if: matrix.python-version == env.PYTHON_MAIN_VERSION
      uses: actions/upload-artifact@v2
      with:
        name: ccaugmentation-dist-py${{ matrix.python-version }}
        path: dist/*
    - name: Generate documentation
      run: |
        pip install pdoc3
        pdoc --html --output-dir docs CCAugmentation
    - name: Deploy documentation
      if: github.ref == 'refs/heads/master' && matrix.python-version == env.PYTHON_MAIN_VERSION
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages
        folder: docs
